DROP TABLE PAYMENT;
DROP TABLE INVOICE;
DROP TABLE CONTRACT;
DROP TABLE CUSTOMER;
DROP TABLE SUBSCRIPTION;

DROP TRIGGER UPDATE_INVOICE_AMOUNT;
DROP TRIGGER UPDATE_INVOICE_STATUS;

DROP FUNCTION GET_UNPAID_INVOICES;
DROP TYPE INVOICE_TABLE;
DROP TYPE INVOICE_ROW;
